### ISSUE TITLE
Repeated answer templates in kiosk.option table

### ISSUE THREAD

**Issue by ryantanaka** [erdl/survey_display#14]
Answer templates (option table) should only occur once for the kiosk.responses associated to them.

**Comment by carlosparadis** [comment]
I verified with Eileen why the answers look repeated, but in fact, the responses do have (or not) the "neutral" option. This was cited in the report that will be sent to Jim. The apparently repeated responses were to facilitate adding or not neutral buttons later in the survey if we needed.

In essence, we would like to not keep neutrals to force people to take an instance and give an opinion on their thermal sensation or discomfort.
