### ISSUE TITLE
Verify if survey_admin or survey_display uses `user` or `users`

### ISSUE THREAD

**Issue by ryantanaka** [erdl/survey_display#15]
@carlosviansi  can you query the user table to see if your name appears as a value. 

![screenshot from 2017-09-27 13-37-32](https://user-images.githubusercontent.com/19616012/30942865-0e9a5442-a389-11e7-8b7b-5ded726f873f.png)

**Comment by carlosparadis** [comment]
I get `carlos`. The creepiest code behavior I ever seen.

**Comment by ryantanaka** [comment]
looks like it may be a built in thing. This [post](https://dba.stackexchange.com/questions/75551/returning-rows-in-postgresql-with-a-table-called-user) might give us some insight. I think it's something on the postgres side. Even though I didn't copy `user` into my database, I can still query (`select * from user` and alternatively `select * from current_user`) it and it will return my username.

**Comment by carlosparadis** [comment]
I see. I wonder if some plugin either `survey_display` or `survey_admin` added this to the database?

**Comment by ryantanaka** [comment]
Hmm, I think it may be built in as a system information function. See [section 9.25 System Information Functions](https://www.postgresql.org/docs/9.5/static/functions-info.html) of the postgresql docs. And if this  is the case, then we know that `survey_admin` should be the one using  the `users` table.

**Comment by ryantanaka** [comment]
> And if this is the case, then we know that survey_admin should be the one using the users table.

`survey_admin` is indeed the one using `users`

[Allie's code referencing the users table](https://github.com/erdl/survey_admin/blob/7f66d44887a41802f515581db65c536a067b9327/ubuntuStation/models.py#L22)

**Comment by carlosparadis** [comment]
I edited above to use the reference to ERDL instead of your fork. Weirdly, it is not rending to show the code as it did in another issue. Maybe the code must be versioned within the same repo. 

Also, what about `survey_display`?

**Comment by ryantanaka** [comment]
Okay will do. And I'll edit that comment to our repo's link instead.

I did not see any code that executes a sql command to grab information from the `users` table. The only sql operations that I'm aware of at this moment is this [one in psql.py](https://github.com/erdl/survey_display/blob/e5c27832d874af064d110d934be9a9d56e5e3c23/occquse/utils/psql.py#L9) being done to grab survey info. When I cloned the database to my computer, I did not include the `users` table. So far the program still runs as intended without that table.

**Comment by carlosparadis** [comment]
Do you have `survey_admin` local yet?

**Comment by ryantanaka** [comment]
i have survey admin running locally now, this was without the creation of a `user` table, and  was able to login to the app locally

**Comment by carlosparadis** [comment]
I tried deleting the user table locally, the one not used by `survey_admin`, but it didn't work, said i typed wrong syntax. Are you able to? Even if this is a sys. table. i dont know why only appears in this database.

**Comment by ryantanaka** [comment]
@carlosparadis , sorry didn't see this comment, I can give it a try tomorrow

**Comment by carlosparadis** [comment]
@ryantanaka We should check with Justin what is this about. We exhausted our searching options at this point!

**Comment by jdelp** [comment]
Fixed with:
DROP table "user";

**Comment by ryantanaka** [comment]
Issue Resolved:

The answer was actually in a stackoverflow link we posted up there but did not read closely enough (my fault..) 

Postgres user defined tables can be accessed by putting quotes around the table name. Omitting the quotes means that it thinks we are addressing a postgres defined table...

The table has been deleted so I am closing this.
