### ISSUE TITLE
Add dynamic color scheme to option buttons

### ISSUE THREAD

**Issue by ryantanaka** [erdl/survey_display#17]
- need to be able to edit the color of the buttons via the database
- HEX color column must be added to `kiosk.options` 
- HEX colors must be retrieved and embedded into the option buttons as a styling

Notes from Eileen & Jim on what they want:

![new doc 2017-11-07 13 17 16_1 1](https://user-images.githubusercontent.com/19616012/32523255-a3ee20d2-c3be-11e7-91f0-59483e24b2ef.jpg)

Notes for myself:

Elm test code to style buttons. Will look at how to work this into our existing code. 

Currently working through Elm [docs](https://guide.elm-lang.org/architecture/effects/random.html).

great [video](https://www.youtube.com/watch?v=HDkyvVfTGEU) explaining Elm type aliases

[Article](http://rundis.github.io/blog/2016/elm_maybe.html) explaining `Maybe`

[Anonymous function explanation](https://dennisreimann.de/articles/elm-functions.html) <- will need this to map options to buttons in `Components.elm`

![elm_add_css](https://user-images.githubusercontent.com/19616012/32523336-f3efcc5c-c3be-11e7-9ff4-dbf3f1be3f9d.png)

**Comment by ryantanaka** [comment]
status update:

- added HEX color column to my database
- updated `psql.py` to pull hex color 
- currently working on accessing the HEX data on the front end through elm

**Comment by ryantanaka** [comment]
status update: 
- I've updated the elm files to support the coloring of buttons based on values set in the database
   - updated: `Comms.elm`, `Components.elm`, `Types.elm`
- the feature works as we need, however I will be testing it out for a bit before submitting pull requests
- i will need to submit a pull request for the `master branch` which contains the elm files and a pull request for the `deployment branch` that contains the updated flask `.py` files

![buttons](https://user-images.githubusercontent.com/19616012/32813761-d27a5a24-c94f-11e7-8276-1f6bcb906f17.png)

**Comment by carlosparadis** [comment]
@ryantanaka can you confirm the `master` branch does not have the flask portion? If it does it will create an inconsistency of versions. Please let me know before submitting the PR.

**Comment by ryantanaka** [comment]
Conference Call 11/15 notes:

> @ryantanaka can you confirm the master branch does not have the flask portion? If it does it will create an inconsistency of versions. Please let me know before submitting the PR.

Just to recap, we've concluded that the master branch was meant for testing without postgres while the `deployment branch` was meant to be used with postgres. Therefore, we will consider the `deployment branch` as the main one.

points we discussed:
- need to add a border to the buttons when clicked on (border must stay there in the case of a `survey form`)
- need to compile the elm files (`elm-make Main.elm --output=survey-app.js`) and place the javascript file in `/static`
- need to include the updates in `psql.py` for the pull request
- be sure to rebase commits into one before submitting the pull request
