### ISSUE TITLE
Change size of buttons so they are all the same

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/survey_display#18]
Jim would like the buttons on the kiosk to all be the same size, not dependent on the length of the word, stack the words on a button, get all buttons running across on one line if possible.

**Comment by carlosparadis** [comment]
@ryantanaka this one is for you!

**Comment by ryantanaka** [comment]
![css for survey_display](https://user-images.githubusercontent.com/19616012/33046370-c3474356-cdf4-11e7-9ac5-93b90806ac20.png)

update
- need to update css with `vertical-align: middle;`, which fixed my uneven button alignment
- stacking words will be done through elm as we are using that for front end dev
    - currently I intend on doing this with `List.intersperse (br [] []) (list of Html)`

**Comment by carlosparadis** [comment]
This looks aesthetically strange to me, but I guess it is easy on the fingers for something like the `kiosk`!

**Comment by ryantanaka** [comment]
@carlosparadis  Any ideas on something that might look better? I can suggest it to Jim/Eileen or make a mock up as well.

**Comment by carlosparadis** [comment]
@ryantanaka I actually think it is a trade-off between aesthetics and functionality, and it's best to bet on functionality like you did. 

Maybe changing the text font to take more of the square space would improve? Not sure. This is one of the things you need to test to see how the brain reacts!
