### ISSUE TITLE
How do you run the survey_display_server locally for development?

### ISSUE THREAD

**Issue by ryantanaka** [erdl/survey_display#2]
- What dependencies/packages are needed?
- Create a guide that explains how to get the application up and running on your local linux machine for testing and development.

**Comment by ryantanaka** [comment]
note: since I can't add to the wiki yet, I'll leave this here and we can figure out a way of adding to the wikis. 

# How do you run the survey_display_server locally on a linux machine for development and testing?

## Index
- Installing Conda
- Creating a virtual environment with all the necessary packages.
- Running survey_display_server locally 

## Installing Conda
To make development simpler, we will be using a virtual environment and package manager called Conda. Follow these [instructions](https://conda.io/docs/user-guide/install/linux.html) to install Conda on your linux machine. You can also download the packages separately and then run Flask.

## Creating a virtual environment with the necessary packages
To ensure that Conda has been installed, in your terminal, type "conda" and you should see output similar to this:

```
usage: conda [-h] [-V] command ...
conda is a tool for managing and deploying applications, environments and packages.
.
.
```

Next, you will need to create a text file where we will specify the necessary packages. With your terminal still open, type "touch spec-file.txt". With an editor of your choice, copy and paste the following into the file:

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.continuum.io/pkgs/free/linux-64/click-6.7-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/flask-0.12.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/flask-cors-3.0.3-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/itsdangerous-0.24-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jinja2-2.9.6-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libpq-9.5.4-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/markupsafe-1.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/openssl-1.0.2l-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pip-9.0.1-py36_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/psycopg2-2.7.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/python-3.6.2-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/readline-6.2-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/setuptools-27.2.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/six-1.10.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/sqlite-3.13.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/tk-8.5.18-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/werkzeug-0.12.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/wheel-0.29.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/xz-5.2.3-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/zlib-1.2.11-0.tar.bz2
```
Now we are ready to create an environment. 
Type the following command:

`conda create --name myenv --file spec-file.txt`

Where "myenv" will be a name of your choice for the environment. 

Finally, you need to activate this environment so that the packages are available when you run survey_display_server.

Type the following command:

`source activate myenv`

See [here](https://conda.io/docs/user-guide/tasks/manage-environments.html#building-identical-conda-environments) for additional instructions and information on using conda.
The next step is to run server_display_server.

## Running survey_display_server on your machine
**With your conda environment activated**, navigate to the root directory of the project. Ensure that you are on the **master branch** of the project. Run the following command:

`./run.sh`

If everything went well, you can expect the following output:

```
 * Serving Flask app "server"
 * Forcing debug mode on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 232-600-007
```
In your browser, go to this link to see the page:

`http://127.0.0.1:5000/surveys/test-survey`

**Comment by ryantanaka** [comment]
moved to [Wiki](https://github.com/erdl/survey_display_server/wiki/How-do-you-run-locally-for-development%3F)

**Comment by carlosparadis** [comment]
@ryantanaka I suppose I will close this issue for now. We can discuss more about [Vagrant](vagrantup.com) in a later stage of the project if we decide to maintain the survey display. Issue #4 is too grave and should take the highest priority right now.
