### ISSUE TITLE
Question on what determines the order of questions in the form

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/survey_display#30]
Hi, Guys.
I don't know if this is a display issue or survey admin issue. I'm looking at the order of the questions for a survey in survey admin http://csbcd01.soest.hawaii.edu/survey/74  Survey called IRB list2 deployed at testform1   http://csbcd01.soest.hawaii.edu/surveys/test1form and the order of the questions doesn't match. This is curious but not urgent since there is no immediate plan to deploy the form. Jim plans to deploy the kiosk.
Regards, Eileen
PS I see the table survey_question as a column called question_position and they are all zero. I'm assuming this needs to be incorporated into survey admin - to assign this number according to the order in which we select the questions.

**Comment by carlosparadis** [comment]
@eileenpeppard survey admin issue. I am opening there, referencing this issue and closing it.
