### ISSUE TITLE
Resize buttons so that 7 can fit horizontally on the screen 

### ISSUE THREAD

**Issue by ryantanaka** [erdl/survey_display#48]
Right now, 7 survey options will wrap around the screen (we want everything to show up inline, but one button ends up on the next line). The survey option buttons need to be resized so that up to 7 fit inline.

**Comment by carlosparadis** [comment]
@ryantanaka should we close this?

**Comment by ryantanaka** [comment]
@carlosparadis, yup we can close this one. (pr was accepted a while back, so i will close now)
