### ISSUE TITLE
Display likert scale instead of "Strong Disagree - Strongly Agree" 5 point scale 

### ISSUE THREAD

**Issue by carlosparadis** [erdl/survey_display#5]
This feature was requested by Jim to be shown on the 1-question kiosk version. The [likert scale](https://en.wikipedia.org/wiki/Likert_scale) is discussed here. It looks like this right now:

<img width="941" alt="screenshot 2017-09-08 21 55 10" src="https://user-images.githubusercontent.com/17270563/30238372-26f323ee-94e2-11e7-86a1-9bd6db6a4c73.png">

Across [all kiosk questionnaires](http://csbcd01.soest.hawaii.edu/surveys/test1kiosk). 

I have some concerns with the likert scale. I understand there is a need to have the questions appeal to the users so they use it, but we need to be careful to not compromise the interpretation of the responses, something often criticized on this scale. Maybe we can discuss this at a later meeting. 

On a side note, I found [this article](http://www.labeee.ufsc.br/antigo/arquivos/publicacoes/Thermal_Booklet.pdf
) accidentally which contain nice illustrations in case we ever need it.

## Next Steps

1. Currently, only one button has the emoji. @ryantanaka was it discussed which other emojis were wanted to be used? 

1. I see the text is still being displayed. Is this the intent or removing the text and just leaving the emojis?

1. I was going to ask about changing code directly on production, but I just remembered the change was actually done in the production database. This is still a bit concerning :') We may want to revisit this kind of "database production testing" at some point using the local server we have in ERDL lab..

**Comment by ryantanaka** [comment]
@carlosviansi  in response to  **NEXT STEPS**

> Currently, only one button has the emoji. @ryantanaka was it discussed which other emojis were wanted to be used?

I will talk this over with Eileen, if they really want to use the emoji's, we just need to decide on which ones. 

> I see the text is still being displayed. Is this the intent or removing the text and just leaving the emojis?

I believe the intent was to have both so that there is no room for misinterpretation, but I will double check.

> I was going to ask about changing code directly on production, but I just remembered the change was actually done in the production database. This is still a bit concerning :') We may want to revisit this kind of "database production testing" at some point using the local server we have in ERDL lab..

Now that I have the database running locally (see this [guide](https://github.com/erdl/survey_display/wiki/Running-in-Localhost)), this won't be an issue anymore. All changes will be tested out locally before touching the production database.

**Comment by carlosparadis** [comment]
> Now that I have the database running locally (see this guide), this won't be an issue anymore. All changes will be tested out locally before touching the production database. 

Amen to that. 

Since the production repo is also clean, we can just pull the requests from Github from there too, so everything it is integrated. Once the local server is online, we will just link it also this remote and have it pull the code before we pull from production. So much easier and saner than sending hundreds of files via sftp! 

As agreed, I am moving this to Low priority, in the interest of the issues who have code base change. If they decide to ask you about this and they deem more important than the other tasks (make sure you enlighten then on our rationale!), then feel free to switch this to normal or even high.

**Comment by carlosparadis** [comment]
We decided not to add smiley faces in the end because we deem sufficient the changes to the buttons, coloring, etc #17.
