### ISSUE TITLE
Update folder names on the server to survey_display

### ISSUE THREAD

**Issue by carlosparadis** [erdl/survey_display#9]
This may look cosmetics but there is a deeper meaning to this: We need to get a better sense of what breaks if we rename/edit and what doesn't since we decided to move forward in maintaining this project.

I know some crawlers make assumptions on the original name the folder was created, and I wouldn't be surprised if `Flask` acts similarly. 

This is also a good opportunity to create `tests`. The question, however, is how if at all possible. Minimally, we should at least have a document with things that need to be done before any major release on it-vm.

**Comment by carlosparadis** [comment]
@ryantanaka We should change the folder names before the surveys are deployed since this can potentially wreck the survey. `Deadline for deployment is January 19, 2018`.

**Comment by ryantanaka** [comment]
update:

I've updated the folder names and code to work with the name changes from `occquse` to `survey_display`. Currently testing it out on my machine. So far so good.

**Comment by ryantanaka** [comment]
@ryantanaka, double check this then close.

**Comment by ryantanaka** [comment]
Ran some tests after https://github.com/erdl/legacy-scrape-util/pull/25 had been accepted.  Survey_display is working properly with the folder name changes.
